# Generated by Django 4.1 on 2022-09-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_profile_delete_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='link_pagina_web',
            new_name='webpage_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='descripcion',
            new_name='description',
        ),
    ]